
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action ListOfSelectedProductsAction;

	private global::Gtk.Action ListOfSelectedProductsAction1;

	private global::Gtk.Action ClearAction;

	private global::Gtk.Action DeleteLastRowAction;

	private global::Gtk.Action CalculateTotalPriceAction;

	private global::Gtk.VBox vbox5;

	private global::Gtk.MenuBar menubar3;

	private global::Gtk.HBox hbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeview1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.ComboBox combobox1;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button searchButton;

	private global::Gtk.Image image1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.ListOfSelectedProductsAction = new global::Gtk.Action("ListOfSelectedProductsAction", global::Mono.Unix.Catalog.GetString("List of selected products"), null, null);
		this.ListOfSelectedProductsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("List of selected products");
		w1.Add(this.ListOfSelectedProductsAction, null);
		this.ListOfSelectedProductsAction1 = new global::Gtk.Action("ListOfSelectedProductsAction1", global::Mono.Unix.Catalog.GetString("List of selected products"), null, null);
		this.ListOfSelectedProductsAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("List of selected products");
		w1.Add(this.ListOfSelectedProductsAction1, null);
		this.ClearAction = new global::Gtk.Action("ClearAction", global::Mono.Unix.Catalog.GetString("Clear"), null, null);
		this.ClearAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Clear");
		w1.Add(this.ClearAction, null);
		this.DeleteLastRowAction = new global::Gtk.Action("DeleteLastRowAction", global::Mono.Unix.Catalog.GetString("Delete last row"), null, null);
		this.DeleteLastRowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete last row");
		w1.Add(this.DeleteLastRowAction, null);
		this.CalculateTotalPriceAction = new global::Gtk.Action("CalculateTotalPriceAction", global::Mono.Unix.Catalog.GetString("Calculate total price"), null, null);
		this.CalculateTotalPriceAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Calculate total price");
		w1.Add(this.CalculateTotalPriceAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Products selection");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("ProductsSelectionProject.bin.Debug.Linux.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar3'><menu name='ListOfSelectedProductsAction1' action='ListOfSelectedProductsAction1'><menuitem name='ClearAction' action='ClearAction'/><menuitem name='DeleteLastRowAction' action='DeleteLastRowAction'/><menuitem name='CalculateTotalPriceAction' action='CalculateTotalPriceAction'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox5.Add(this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView();
		this.treeview1.WidthRequest = 235;
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow.Add(this.treeview1);
		this.hbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.WidthRequest = 235;
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Search by product type"));
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Search by company-producer"));
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.vbox1.Add(this.combobox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.combobox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vbox1.Add(this.entry1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.searchButton = new global::Gtk.Button();
		this.searchButton.CanFocus = true;
		this.searchButton.Name = "searchButton";
		this.searchButton.UseUnderline = true;
		this.searchButton.Label = global::Mono.Unix.Catalog.GetString("Search");
		this.vbox1.Add(this.searchButton);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.searchButton]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("ProductsSelectionProject.bin.Debug.Linux.png");
		this.vbox1.Add(this.image1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.image1]));
		w8.Position = 3;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.WidthRequest = 235;
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.textview1.CursorVisible = false;
		this.GtkScrolledWindow1.Add(this.textview1);
		this.vbox3.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow1]));
		w11.Position = 0;
		this.vbox2.Add(this.vbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
		w12.Position = 0;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w13.Position = 2;
		this.vbox5.Add(this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
		w14.Position = 1;
		this.Add(this.vbox5);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 762;
		this.DefaultHeight = 550;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ClearAction.Activated += new global::System.EventHandler(this.LOSPClearMenuItemActivated);
		this.DeleteLastRowAction.Activated += new global::System.EventHandler(this.LOSPDeleteLastRowMenuItemActvated);
		this.CalculateTotalPriceAction.Activated += new global::System.EventHandler(this.LOSPCalculateTotalPriceMenuItemActivated);
		this.treeview1.RowActivated += new global::Gtk.RowActivatedHandler(this.treeview1RowActivated);
		this.searchButton.Clicked += new global::System.EventHandler(this.searchButtonClicked);
	}
}
